default_model: 1.7B-CustomVoice
models:
  0.6B-Base:
    hf_id: Qwen/Qwen3-TTS-12Hz-0.6B-Base
    type: base
  0.6B-CustomVoice:
    hf_id: Qwen/Qwen3-TTS-12Hz-0.6B-CustomVoice
    type: customvoice
  1.7B-Base:
    hf_id: Qwen/Qwen3-TTS-12Hz-1.7B-Base
    type: base
  1.7B-CustomVoice:
    hf_id: Qwen/Qwen3-TTS-12Hz-1.7B-CustomVoice
    type: customvoice
optimization:
  attention: flash_attention_2
  compile_mode: reduce-overhead
  use_compile: true
  use_cuda_graphs: false
  use_fast_codebook: true
  compile_talker: false  # with disable it's 0.7RTF
  streaming:
    decode_window_frames: 64
    emit_every_frames: 4
  compile_codebook_predictor: true
server:
  host: 0.0.0.0
  port: 8880
voices:
- language: Chinese
  name: Vivian
- language: Chinese
  name: Serena
- language: Chinese
  name: Uncle_Fu
- language: Chinese
  name: Dylan
- language: Chinese
  name: Eric
- language: English
  name: Ryan
- language: Japanese
  name: Aiden
- language: Korean
  name: Ono_Anna
- language: English
  name: Sohee
